AnimalShelter/Models/Animal.cs
using System;
using System.Collections.Generic;


namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }  
    public string Gender { get; set; }
    public string Type { get; set; }
    public DateTime Date { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals
      .OrderBy(x => x.Type)
      .ThenBy(x => x.Date)
      .ToList();
      
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add a New Animal</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Gender)
  @Html.TextBoxFor(model => model.Gender)

  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)

  @Html.LabelFor(model => model.Date)
  @Html.TextBoxFor(model => model.Date)

  <input type="submit" value="Add New Animal" />
}
<p>@Html.ActionLink("Show all Animals", "Index")</p>

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)<h3>
<h3>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)<h3>
<h3>@Html.DisplayNameFor(model => model.Date): @Html.DisplayFor(model => model.Date)<h3>
<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Animal>;

<h1>Animals</h1>

<ul>
  @foreach(Animal animal in Model)
  {
      <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.Gender}", "Details", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.Type}", "Details", new { id = animal.AnimalId })</li>
      <li>@Html.ActionLink($"{animal.Date}", "Details", new { id = animal.AnimalId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new animal", "Create")</p>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Animal Shelter!</h1>
<p>@Html.ActionLink("See all animals", "Index", "Animals")</p> 

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>Animal Shelter
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>